### ISSUE TITLE
Pixart Support

### ISSUE THREAD

**Issue by theCosmicCrafter** [city96/SD-Latent-Interposer#12]
I absolutely love your work and everything you do for the community! Do you have any plans to add support for Picsart to this project?

**Comment by city96** [comment]
PixArt alpha uses the SDv1 VAE (latent_src: `v1`) and PixArt sigma uses the SDXL VAE (latent_src: `xl`) so it's already supported without any extra changes.

Feel free to reopen if that's not what you meant lol
