### ISSUE TITLE
Flux Support?

### ISSUE THREAD

**Issue by c0yotte** [city96/SD-Latent-Interposer#13]
Hey, do you have plans on adding a support for Flux? Like Flux latents -> SDXL latents and vice versa? Is that even possible? Thanks for the reply in advance

**Comment by city96** [comment]
Training flux -> v1/xl/v3 as we speak, those are fairly easy to do. Will test how feasible it is the other way around, should have something by tomorrow.

**Comment by city96** [comment]
Well, added it in the direction that makes the most sense, which is flux being the source. The other way around seemed pretty rough, probably better off just vae decoding/encoding.

Closing for now but feel free to reopen if you'd like me to try again for v1/xl/v3->flux lol

**Comment by AugmentedRealityCat** [comment]
I would love to see v1/XL to Flux happen if this is something you are still considering. It might seem silly, but I was just about to do that and I discovered that it was not possible.
