### ISSUE TITLE
[feature request] StableCascade

### ISSUE THREAD

**Issue by MoonMoon82** [city96/SD-Latent-Interposer#6]
After StableCascade has been introduced natively in comfyUI, a direct conversion from stage_b latent to SDXL or SD1.5 latent format would be very useful!
But I need to admit, I have no idea if it's even possible..

**Comment by city96** [comment]
>But I need to admit, I have no idea if it's even possible..

I mean, it should be, if you don't mind the quality being sub-par. I only did a quick test w/ stage C so far to see if I could ditch stage B completely, and that seemed to kinda-sorta work.

![image](https://github.com/city96/SD-Latent-Interposer/assets/125218114/2de3e807-cf11-4a6e-a453-b8d427b5bebf)

**Comment by MoonMoon82** [comment]
@city96 Sounds interesting! But I don't think it's a good idea to connect to stage_c latent, because - of what I understood - stage_c latent is compressed and stage_b takes over the decoding of the compressed latent. The latent output of stage_b would then be more in my focus.

**Comment by city96** [comment]
@MoonMoon82 Hi, a bit late but I finished training some models for stage_b. Also redid the v1/xl stuff to be slightly better. Can you test it if you have the time? They're on the [`experimental` branch](https://github.com/city96/SD-Latent-Interposer/tree/experimental) for now but I'll merge them to main if everything looks fine.

Edit: Make sure your comfyui is version d7897ff or later for the cascade one.
