### ISSUE TITLE
convert sd1.5 lora to sdxl?

### ISSUE THREAD

**Issue by ballenvironment** [city96/SD-Latent-Interposer#7]
I found your project looking to an answer to my question - how to convert an sd1.5 lora into sdxl. 

From what I found it doesn't seem to be possible without retraining a new model which is a bummer since 90% of models are for 1.5. I'm not expecting a high quality conversion either just getting them to run would be fine.

Do you think its possible to write a converter, possibly with use of this repo?

**Comment by city96** [comment]
I think what you're looking for is [X-adapter](https://github.com/showlab/X-Adapter) but I don't think it has a proper ComfyUI plugin outside [this one](https://github.com/kijai/ComfyUI-Diffusers-X-Adapter), which is just a wrapper around diffusers.

**Comment by ballenvironment** [comment]
Thanks! That's what I was looking for.
